{% set name = "mappyfile" %}
{% set version = "1.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 9a846d04ded66a792138767a6a1f7bbf0807396a61550d18d1977a40aba6519c

build:
  number: 0
  noarch: python
  entry_points:
    - mappyfile=mappyfile.cli:main
  script: "{{ PYTHON }} -m pip install . -vv"


requirements:
  host:
    - pip
    - python >=3.8
  run:
    - click
    - jsonref ==1.1.0
    - jsonschema >=4.18.0
    - lark >=1.1.5
    - setuptools
    - python >=3.8

test:
  imports:
    - mappyfile
  requires:
    - pip
  commands:
    - pip check
    - mappyfile --help

about:
  home: "http://github.com/geographika/mappyfile"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A pure Python MapFile parser for working with MapServer"
  doc_url: https://mappyfile.readthedocs.io/en/latest
  dev_url: http://github.com/geographika/mappyfile

extra:
  recipe-maintainers:
    - geographika
    - tchaddad
