{% set name = "mappyfile" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 4dbdb49838d69189727859a42cfaae29dd1a193b71bd0d5c2c62a93b8c944eda

build:
  number: 0
  noarch: python
  entry_points:
    - mappyfile=mappyfile.cli:main
  script: "{{ PYTHON }} -m pip install . -vv"


requirements:
  host:
    - pip
    - python >=3.8
  run:
    - click
    - jsonref ==0.2
    - jsonschema >=2.0
    - lark-parser >=0.11.3
    - setuptools
    - python >=3.8

test:
  imports:
    - mappyfile
  requires:
    - pip
  commands:
    - pip check
    - mappyfile --help

about:
  home: "http://github.com/geographika/mappyfile"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A pure Python MapFile parser for working with MapServer"
  doc_url: https://mappyfile.readthedocs.io/en/latest
  dev_url: http://github.com/geographika/mappyfile

extra:
  recipe-maintainers:
    - geographika
    - tchaddad
